In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/ass3.csv')

In [ ]:
print(df)

    roll name  age gen branch sec
0      1    a   20   m    cse   a
1      2    b   21   f    cse   d
2      3    c   22   m    cse   b
3      4    d   23   m    cse   c
4      5    e   20   m    cse   e
5      6    f   20   f    cse   f
6      7    g   19   f    cse   a
7      8    h   19   f    cse   d
8      9    i   22   m    cse   d
9     10    j   21   m    cse   c
10    11    k   24   m    cse   a
11    12    l   20   f    cse   e
12    13    m   20   m    cse   b
13    14    n   24   f    cse   b
14    15    o   21   f    cse   f

In [ ]:
df.head()

   roll name  age gen branch sec
0     1    a   20   m    cse   a
1     2    b   21   f    cse   d
2     3    c   22   m    cse   b
3     4    d   23   m    cse   c
4     5    e   20   m    cse   e

In [ ]:
df.tail()

    roll name  age gen branch sec
10    11    k   24   m    cse   a
11    12    l   20   f    cse   e
12    13    m   20   m    cse   b
13    14    n   24   f    cse   b
14    15    o   21   f    cse   f

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    15 non-null     int64
 1   name    15 non-null     object
 2   age     15 non-null     int64
 3   gen     15 non-null     object
 4   branch  15 non-null     object
 5   sec     15 non-null     object
dtypes: int64(2), object(4)
memory usage: 852.0+ bytes

In [ ]:
df.describe()

            roll        age
count  15.000000  15.000000
mean    8.000000  21.066667
std     4.472136   1.624221
min     1.000000  19.000000
25%     4.500000  20.000000
50%     8.000000  21.000000
75%    11.500000  22.000000
max    15.000000  24.000000

In [ ]:
df.shape

(15, 6)

In [ ]:
df.columns

Index(['roll', 'name', 'age', 'gen', 'branch', 'sec'], dtype='object')

In [ ]:
df.dtypes

roll       int64
name      object
age        int64
gen       object
branch    object
sec       object
dtype: object

In [ ]:
df.isnull().sum()

roll      0
name      0
age       0
gen       0
branch    0
sec       0
dtype: int64

In [ ]:
df.iloc[2]

roll        3
name        c
age        22
gen         m
branch    cse
sec         b
Name: 2, dtype: object

In [ ]:
df.loc(0)

In [ ]:
ages=df['age']

In [ ]:
ages

0     20
1     21
2     22
3     23
4     20
5     20
6     19
7     19
8     22
9     21
10    24
11    20
12    20
13    24
14    21
Name: age, dtype: int64

In [ ]:
adults=df[df['age']>20]

In [ ]:
adults

    roll name  age gen branch sec
1      2    b   21   f    cse   d
2      3    c   22   m    cse   b
3      4    d   23   m    cse   c
8      9    i   22   m    cse   d
9     10    j   21   m    cse   c
10    11    k   24   m    cse   a
13    14    n   24   f    cse   b
14    15    o   21   f    cse   f

In [ ]:
adults=df[(df['age']>19) & (df['age']< 23)]

In [ ]:
adults

    roll name  age gen branch sec
0      1    a   20   m    cse   a
1      2    b   21   f    cse   d
2      3    c   22   m    cse   b
4      5    e   20   m    cse   e
5      6    f   20   f    cse   f
8      9    i   22   m    cse   d
9     10    j   21   m    cse   c
11    12    l   20   f    cse   e
12    13    m   20   m    cse   b
14    15    o   21   f    cse   f